[tool.poetry]
name = "inoopa_utils"
description = "Collection of utils used at Inoopa."
version = "1.11.2"
authors = ["Dev Inoopa <dev@inoopa.com>"]
packages = [{ include = "inoopa_utils" }]
repository = "https://bitbucket.org/inoopa/inoopa_utils/"
readme = "README.md"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
python = "^3.11"
iniconfig = "^2.0.0"
numpy = "^1.20.0"
packaging = "^23.0"
pamqp = "^2.0.0"
pandas = "^2.0.0"
pluggy = "^1.0.0"
PyMySQL = "^1.0.0"
pytest = "^7.0.0"
python-dateutil = "^2.0.0"
pytz = "^2023"
rabbitpy = "^2.0.1"
six = "^1.0.0"
SQLAlchemy = "^2.0.0"
typesense = "^0.18.0"
typing_extensions = "^4.0.0"
tzdata = "^2023"
pymongo = "^4.6.1"
