[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
version = "1.0.0"
name = "d2-dome"
authors = [{name = "Bhavin Dave", email = "bhavin.dave@declarativedata.com"}]
requires-python = ">=3.8"
license = {file = "LICENSE"}
classifiers = ["License :: OSI Approved :: MIT License"]
dynamic = ["description"]
dependencies = [
    "pandas >= 2.1.1",
]

[project.urls]
Home = "https://declarativedata.com/"

[tool.flit.module]
name="dome"

[tool.poetry]
readme = "README.md"
