[tool.poetry]
name = "criticalmaas.ta1-geopackage"
version = "0.1.0"
description = "GeoPackage schema for validating and storing vector geologic map data produced by computer-vision pipelines"
authors = ["Daven Quinn <code@davenquinn.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "criticalmaas"}]



[tool.poetry.dependencies]
python = "^3.10"
fiona = "^1.9.5"
geopandas = "^0.14.1"
"macrostrat.database" = "^3.0.0"
macrostrat-utils = "^1.2.0"


[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"

[tool.poetry.group.schema-diagram]
optional = true

[tool.poetry.group.schema-diagram.dependencies]
sadisplay = { path = "./deps/sadisplay", develop = true }

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
