[tool.poetry]
name = "shruvi-math-library"
version = "0.1.0"
description = ""
authors = ["shruvi.shah <shruvi.shah@crestdatasys.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
