





#
#	how to publish:
#
#		python3 status/status.py
#		(rm -rf dist && python3 -m build --sdist && twine upload dist/*)
#

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "winrate"
version = "1.0.0"
dependencies = []

# license = { text = "license" }
license = { file = "license.txt" }

description = "economic estimation"
readme = "structure.txt"
keywords = [	 
	"economic estimation",
	"finance",
	"commerce",
	"wealth",
	"money",
	"treasures",
	"treasury",
	"subconscious trading"
]

[project.scripts]
#
#	https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#creating-executable-scripts
#	from this_module import clique; clique ()
#
# 	this_module = "this_module:clique"
#

[tool.setuptools.packages.find]
where = [ "structures/modules" ]

#
#	https://setuptools.pypa.io/en/latest/userguide/datafiles.html
#
[tool.setuptools.package-data]
"*" = [ "*.html" ]




