[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "pygranta"
description = "Pythonic interfaces to Ansys Granta MI"
version = "2023.2.0rc0"
license = "MIT"
authors = ["ANSYS, Inc. <pyansys.core@ansys.com>"]
maintainers = ["ANSYS, Inc. <pyansys.core@ansys.com>"]
repository = "https://github.com/ansys/pygranta"
documentation = "https://grantami.docs.pyansys.com"
readme = "README.rst"
classifiers = [
  "Development Status :: 4 - Beta",
  "Intended Audience :: Science/Research",
  "Topic :: Scientific/Engineering :: Information Analysis",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
]
packages = [{ include = "**/*.py", from = "src" }]

[tool.poetry.dependencies]
python = "^3.8"
ansys-grantami-bomanalytics = "1.2.0"
ansys-grantami-bomanalytics-openapi = "1.1.0"
ansys-grantami-recordlists = "1.0.0.post1"
ansys-grantami-serverapi-openapi = "1.0.0"

# Optional documentation dependencies
[tool.poetry.group.doc]
optional = true

[tool.poetry.group.doc.dependencies]
Sphinx = "^7.0.1"
ansys-sphinx-theme = "^0.12.1"
sphinx-copybutton = "^0.5.0"
sphinx-design = "^0.5.0"

[tool.black]
line-length = 100

[tool.isort]
profile = "black"
force_sort_within_sections = true
line_length = 100
