[default]
CREDIT_SCORING_URL = 'https://plumber.spectral.finance/api/v1/{0}/features'
CREDIT_SCORING_BATCH_URL = 'https://plumber.spectral.finance/api/v1/features_batch'
SPECTRAL_API_KEY = 'placeholder_api_key'
NUM_RETRIES = 3
NUM_ITEMS_PER_BATCH_REQUEST = 4000
