[build-system]
requires = ["setuptools>=40.8.0","wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "jgtapy"
version = "1.9.18"
authors = [
  { name="JGWill", email="jgi@jgwill.com" },
]
description = "Enhanced JGTapy"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/jgwill/jgtapy"
"Bug Tracker" = "https://github.com/jgwill/jgtapy/issues"
