name: AmbuView_venv
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.10
  - numpy=1.26.3
  - osmnx=1.8.1
  - networkx=3.2.1
  - folium=0.15.1
  - alphashape=1.3.1
  - requests=2.31.0
  - pandas=2.1.4
  - geopandas=0.14.1
  - shapely=2.0.2
  - scipy=1.11.4
  - setuptools=60.2.0
  - scikit-learn=1.3.2
  - geopy=2.4.1